language: node_js
cache: npm
node_js:
  - 8
  - 10
  - 12

stages:
  - lint
  - test
  - name: release
    if: branch =~ /^(\d+\.x|master)$/ AND type IN (push)

jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
